/* Generated with cbindgen:0.29.0 */

/* This file is automatically generated by cbindgen. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

extern "C" {
/**
 * Free a single C string returned by the transform functions
 */
void free_c_string(char *s);

char *cruet_to_class_case(const char *s);

char *cruet_to_camel_case(const char *s);

char *cruet_to_pascal_case(const char *s);

char *cruet_to_screamingsnake_case(const char *s);

char *cruet_to_snake_case(const char *s);

char *cruet_to_kebab_case(const char *s);

char *cruet_to_train_case(const char *s);

char *cruet_to_sentence_case(const char *s);

char *cruet_to_title_case(const char *s);

char *cruet_to_upper_case(const char *s);

char *cruet_to_lower_case(const char *s);

char *cruet_to_table_case(const char *s);

char *cruet_ordinalize(const char *s);

char *cruet_deordinalize(const char *s);

char *cruet_to_foreign_key(const char *s);

char *cruet_demodulize(const char *s);

char *cruet_deconstantize(const char *s);

char *cruet_to_plural(const char *s);

char *cruet_to_singular(const char *s);

unsigned char cruet_is_class_case(const char *s);

unsigned char cruet_is_camel_case(const char *s);

unsigned char cruet_is_pascal_case(const char *s);

unsigned char cruet_is_screamingsnake_case(const char *s);

unsigned char cruet_is_snake_case(const char *s);

unsigned char cruet_is_kebab_case(const char *s);

unsigned char cruet_is_train_case(const char *s);

unsigned char cruet_is_sentence_case(const char *s);

unsigned char cruet_is_title_case(const char *s);

unsigned char cruet_is_table_case(const char *s);

unsigned char cruet_is_foreign_key(const char *s);
}